// Redux Actions
export const CREATE_SHIPPING = 'CREATE_SHIPPING';
export const SHIPPING_USE_DOCUMENT = 'SHIPPING_USE_DOCUMENT';
export const SHIPPING_SET_ARIANE_OPERATION = 'SHIPPING_SET_ARIANE_OPERATION';
export const SHIPPING_CANCEL_ARIANE_OPERATION = 'SHIPPING_CANCEL_ARIANE_OPERATION';
export const SELECT_CARRIER = 'SELECT_CARRIER';
export const CANCEL_CARRIER_SELECTION = 'CANCEL_CARRIER_SELECTION';
export const SELECT_DESTINATION_TYPE = 'SELECT_DESTINATION_TYPE';
export const CANCEL_DESTINATION_TYPE_SELECTION = 'CANCEL_DESTINATION_TYPE_SELECTION';
export const SELECT_SUPPLIER = 'SELECT_SUPPLIER';
export const CANCEL_SUPPLIER_SELECTION = 'CANCEL_SUPPLIER_SELECTION';
export const SELECT_TREATMENT_SITE = 'SELECT_TREATMENT_SITE';
export const CANCEL_TREATMENT_SITE_SELECTION = 'CANCEL_TREATMENT_SITE_SELECTION';
export const SHIPPING_SAVED = 'SHIPPING_SAVED';
// Shipping containers selection
export const SHIPPING_ADD_CONTAINER = 'SHIPPING_ADD_CONTAINER';
export const SHIPPING_REPLACE_SELECTED_CONTAINER = 'SHIPPING_REPLACE_SELECTED_CONTAINER';
export const SHIPPING_REMOVE_SELECTED_CONTAINER = 'SHIPPING_REMOVE_SELECTED_CONTAINER';
export const SHIPPING_CONFIRM_SELECTED_CONTAINERS = 'SHIPPING_CONFIRM_SELECTED_CONTAINERS';
export const SHIPPING_CANCEL_CONTAINERS_SELECTION = 'SHIPPING_CANCEL_CONTAINERS_SELECTION';
// Shipping: Trackdéchets bordereaux
export const SHIPPING_BATCH_SCAN_TRACKDECHETS_BORDEREAUX_CONFIRM =
  'SHIPPING_BATCH_SCAN_TRACKDECHETS_BORDEREAUX_CONFIRM';
export const SHIPPING_BATCH_SCAN_TRACKDECHETS_BORDEREAUX_CANCEL = 'SHIPPING_BATCH_SCAN_TRACKDECHETS_BORDEREAUX_CANCEL';
export const SHIPPING_SET_CARRIER_LICENSE_PLATE = 'SHIPPING_SET_CARRIER_LICENSE_PLATE';

// Scenes
export const PIPE_SHIPPING_DOCUMENT_SHUNT = 'pipe_shipping_document_shunt';
export const PIPE_SHIPPING_SCAN_DOCUMENT = 'pipe_shipping_scan_document';
export const PIPE_SHIPPING_BATCH_SCAN_CONTAINERS = 'pipe_shipping_batch_scan_containers';
export const PIPE_SHIPPING_SCAN_ARIANE_OPERATION_CONTAINERS = 'pipe_shipping_scan_ariane_operation_containers';
export const PIPE_SHIPPING_SUMUP = 'pipe_shipping_sumup';
export const PIPE_SHIPPING_SELECT_CARRIER = 'pipe_shipping_select_carrier';
export const PIPE_SHIPPING_SELECT_DESTINATION_TYPE = 'pipe_shipping_select_destination_type';
export const PIPE_SHIPPING_SUPPLIER_SELECTION = 'pipe_shipping_supplier_selection';
export const PIPE_SHIPPING_TREATMENT_SITE_SELECTION = 'pipe_shipping_treatment_site_selection';
export const PIPE_SHIPPING_BATCH_SCAN_TRACKDECHETS_BORDEREAUX = 'pipe_shipping_batch_scan_trackdechets_bordereaux';
export const PIPE_SHIPPING_AUTO_FETCH_TRACKDECHETS_BORDEREAUX = 'pipe_shipping_auto_fetch_trackdechets_bordereaux';
export const PIPE_SHIPPING_SELECT_LICENSE_PLATE = 'pipe_shipping_select_license_plate';
