// Redux Actions
export const INTERVENTION_CREATE = 'INTERVENTION_CREATE';
export const INTERVENTION_PURPOSE = 'INTERVENTION_PURPOSE';
export const INTERVENTION_SET_CONTAINER_LOAD = 'INTERVENTION_SET_CONTAINER_LOAD';
export const INTERVENTION_ADD_LEAK = 'INTERVENTION_ADD_LEAK';
export const INTERVENTION_CANCEL_LEAK = 'INTERVENTION_CANCEL_LEAK';
export const INTERVENTION_REPAIRED_LEAKS = 'INTERVENTION_REPAIRED_LEAKS';
export const INTERVENTION_MARK_AS_EMPTY = 'INTERVENTION_MARK_AS_EMPTY';
export const INTERVENTION_UPDATE_NOMINAL_LOAD = 'INTERVENTION_UPDATE_NOMINAL_LOAD';
export const INTERVENTION_SHOULD_CREATE_BSFF = 'INTERVENTION_SHOULD_CREATE_BSFF';
export const INTERVENTION_SIGNATURE = 'INTERVENTION_SIGNATURE';
export const INTERVENTION_ADD_COOLANT_CONTAINER = 'INTERVENTION_ADD_COOLANT_CONTAINER';
export const INTERVENTION_REMOVE_COOLANT_CONTAINER = 'INTERVENTION_REMOVE_COOLANT_CONTAINER';
export const INTERVENTION_EDIT_COOLANT_CONTAINER = 'INTERVENTION_EDIT_COOLANT_CONTAINER';
export const INTERVENTION_VALIDATED = 'INTERVENTION_VALIDATED';
export const INTERVENTION_SAVED = 'INTERVENTION_SAVED';
export const INTERVENTION_SIGNED = 'INTERVENTION_SIGNED';
export const INTERVENTION_RESET = 'INTERVENTION_RESET';
// Intervention containers selection
export const INTERVENTION_ADD_CONTAINER_LOAD = 'INTERVENTION_ADD_CONTAINER_LOAD';
export const INTERVENTION_ADD_CONTAINER = 'INTERVENTION_ADD_CONTAINER';
export const INTERVENTION_REMOVE_CONTAINER = 'INTERVENTION_REMOVE_CONTAINER';
export const INTERVENTION_MOVE_CONTAINERS = 'INTERVENTION_MOVE_CONTAINERS';

// Orchestrator Pipes (to be moved)
export const PIPE_PURPOSE = 'purpose';
export const PIPE_CONTAINER_LOAD = 'container_load';
export const PIPE_FILLING_DRAINAGE_SHUNT = 'filling_drainage_shunt';
export const PIPE_LEAK_DETECTION_SHUNT = 'leak_detection_shunt';
export const PIPE_LEAK_REPAIR = 'leak_repair';
export const PIPE_DRAINAGE_FILLING_SUMUP = 'drainage_filling_sum_up';
export const PIPE_LEAK_DETECTION_SUMUP = 'leak_detection_sum_up';
export const PIPE_LEAK_REPAIR_SUMUP = 'leak_repair_sum_up';
export const PIPE_ASSEMBLY_SUMUP = 'assembly_sum_sup';
export const PIPE_DISASSEMBLY_SUMUP = 'disassembly_sum_up';
export const PIPE_SELECT_LEAKING_COMPONENT = 'select_leaking_component';
export const PIPE_LEAK_FORM = 'leak_form';
export const PIPE_MY_INTERVENTIONS = 'my_interventions';
export const PIPE_INTERVENTION_INFOS = 'intervention_infos';
export const INTERVENTION_INVITE_SCAN_CONTAINER = 'intervention_invite_scan_container';
export const PIPE_ANALYSIS_INFOS = 'analysis_infos';
export const PIPE_SELECT_COOLANT_CONTAINERS = 'select_coolant_containers';
export const PIPE_COOLANT_TRANSITION = 'coolant_transition';
