export const CountryNames = {
  en: {
    AF: "Afghanistan",
    AX: "Aland Islands",
    AL: "Albania",
    DZ: "Algeria",
    AS: "American Samoa",
    AD: "Andorra",
    AO: "Angola",
    AI: "Anguilla",
    AQ: "Antarctica",
    AG: "Antigua And Barbuda",
    AR: "Argentina",
    AM: "Armenia",
    AW: "Aruba",
    AU: "Australia",
    AT: "Austria",
    AZ: "Azerbaijan",
    BS: "Bahamas",
    BH: "Bahrain",
    BD: "Bangladesh",
    BB: "Barbados",
    BY: "Belarus",
    BE: "Belgium",
    BZ: "Belize",
    BJ: "Benin",
    BM: "Bermuda",
    BT: "Bhutan",
    BO: "Bolivia",
    BA: "Bosnia And Herzegovina",
    BW: "Botswana",
    BV: "Bouvet Island",
    BR: "Brazil",
    IO: "British Indian Ocean Territory",
    BN: "Brunei Darussalam",
    BG: "Bulgaria",
    BF: "Burkina Faso",
    BI: "Burundi",
    KH: "Cambodia",
    CM: "Cameroon",
    CA: "Canada",
    CV: "Cape Verde",
    KY: "Cayman Islands",
    CF: "Central African Republic",
    TD: "Chad",
    CL: "Chile",
    CN: "China",
    CX: "Christmas Island",
    CC: "Cocos (Keeling) Islands",
    CO: "Colombia",
    KM: "Comoros",
    CG: "Congo",
    CD: "Congo, Democratic Republic",
    CK: "Cook Islands",
    CR: "Costa Rica",
    CI: 'Cote D"Ivoire',
    HR: "Croatia",
    CU: "Cuba",
    CY: "Cyprus",
    CZ: "Czech Republic",
    DK: "Denmark",
    DJ: "Djibouti",
    DM: "Dominica",
    DO: "Dominican Republic",
    EC: "Ecuador",
    EG: "Egypt",
    SV: "El Salvador",
    GQ: "Equatorial Guinea",
    ER: "Eritrea",
    EE: "Estonia",
    ET: "Ethiopia",
    FK: "Falkland Islands (Malvinas)",
    FO: "Faroe Islands",
    FJ: "Fiji",
    FI: "Finland",
    FR: "France",
    GF: "French Guiana",
    PF: "French Polynesia",
    TF: "French Southern Territories",
    GA: "Gabon",
    GM: "Gambia",
    GE: "Georgia",
    DE: "Germany",
    GH: "Ghana",
    GI: "Gibraltar",
    GR: "Greece",
    GL: "Greenland",
    GD: "Grenada",
    GP: "Guadeloupe",
    GU: "Guam",
    GT: "Guatemala",
    GG: "Guernsey",
    GN: "Guinea",
    GW: "Guinea-Bissau",
    GY: "Guyana",
    HT: "Haiti",
    HM: "Heard Island & Mcdonald Islands",
    VA: "Holy See (Vatican City State)",
    HN: "Honduras",
    HK: "Hong Kong",
    HU: "Hungary",
    IS: "Iceland",
    IN: "India",
    ID: "Indonesia",
    IR: "Iran, Islamic Republic Of",
    IQ: "Iraq",
    IE: "Ireland",
    IM: "Isle Of Man",
    IL: "Israel",
    IT: "Italy",
    JM: "Jamaica",
    JP: "Japan",
    JE: "Jersey",
    JO: "Jordan",
    KZ: "Kazakhstan",
    KE: "Kenya",
    KI: "Kiribati",
    KR: "Korea",
    KP: "North Korea",
    KW: "Kuwait",
    KG: "Kyrgyzstan",
    LA: 'Lao People"s Democratic Republic',
    LV: "Latvia",
    LB: "Lebanon",
    LS: "Lesotho",
    LR: "Liberia",
    LY: "Libyan Arab Jamahiriya",
    LI: "Liechtenstein",
    LT: "Lithuania",
    LU: "Luxembourg",
    MO: "Macao",
    MK: "Macedonia",
    MG: "Madagascar",
    MW: "Malawi",
    MY: "Malaysia",
    MV: "Maldives",
    ML: "Mali",
    MT: "Malta",
    MH: "Marshall Islands",
    MQ: "Martinique",
    MR: "Mauritania",
    MU: "Mauritius",
    YT: "Mayotte",
    MX: "Mexico",
    FM: "Micronesia, Federated States Of",
    MD: "Moldova",
    MC: "Monaco",
    MN: "Mongolia",
    ME: "Montenegro",
    MS: "Montserrat",
    MA: "Morocco",
    MZ: "Mozambique",
    MM: "Myanmar",
    NA: "Namibia",
    NR: "Nauru",
    NP: "Nepal",
    NL: "Netherlands",
    AN: "Netherlands Antilles",
    NC: "New Caledonia",
    NZ: "New Zealand",
    NI: "Nicaragua",
    NE: "Niger",
    NG: "Nigeria",
    NU: "Niue",
    NF: "Norfolk Island",
    MP: "Northern Mariana Islands",
    NO: "Norway",
    OM: "Oman",
    PK: "Pakistan",
    PW: "Palau",
    PS: "Palestinian Territory, Occupied",
    PA: "Panama",
    PG: "Papua New Guinea",
    PY: "Paraguay",
    PE: "Peru",
    PH: "Philippines",
    PN: "Pitcairn",
    PL: "Poland",
    PT: "Portugal",
    PR: "Puerto Rico",
    QA: "Qatar",
    RE: "Reunion",
    RO: "Romania",
    RU: "Russian Federation",
    RW: "Rwanda",
    BL: "Saint Barthelemy",
    SH: "Saint Helena",
    KN: "Saint Kitts And Nevis",
    LC: "Saint Lucia",
    MF: "Saint Martin",
    PM: "Saint Pierre And Miquelon",
    VC: "Saint Vincent And Grenadines",
    WS: "Samoa",
    SM: "San Marino",
    ST: "Sao Tome And Principe",
    SA: "Saudi Arabia",
    SN: "Senegal",
    RS: "Serbia",
    SC: "Seychelles",
    SL: "Sierra Leone",
    SG: "Singapore",
    SK: "Slovakia",
    SI: "Slovenia",
    SB: "Solomon Islands",
    SO: "Somalia",
    ZA: "South Africa",
    GS: "South Georgia And Sandwich Isl.",
    ES: "Spain",
    LK: "Sri Lanka",
    SD: "Sudan",
    SR: "Suriname",
    SJ: "Svalbard And Jan Mayen",
    SZ: "Swaziland",
    SE: "Sweden",
    CH: "Switzerland",
    SY: "Syrian Arab Republic",
    TW: "Taiwan",
    TJ: "Tajikistan",
    TZ: "Tanzania",
    TH: "Thailand",
    TL: "Timor-Leste",
    TG: "Togo",
    TK: "Tokelau",
    TO: "Tonga",
    TT: "Trinidad And Tobago",
    TN: "Tunisia",
    TR: "Turkey",
    TM: "Turkmenistan",
    TC: "Turks And Caicos Islands",
    TV: "Tuvalu",
    UG: "Uganda",
    UA: "Ukraine",
    AE: "United Arab Emirates",
    GB: "United Kingdom",
    US: "United States",
    UM: "United States Outlying Islands",
    UY: "Uruguay",
    UZ: "Uzbekistan",
    VU: "Vanuatu",
    VE: "Venezuela",
    VN: "Vietnam",
    VG: "Virgin Islands, British",
    VI: "Virgin Islands, U.S.",
    WF: "Wallis And Futuna",
    EH: "Western Sahara",
    YE: "Yemen",
    ZM: "Zambia",
    ZW: "Zimbabwe",
  },
  fr: {
    AF: "Afghanistan",
    ZA: "Afrique du Sud",
    AL: "Albanie",
    DZ: "Algérie",
    DE: "Allemagne",
    AD: "Andorre",
    AO: "Angola",
    AI: "Anguilla",
    AQ: "Antarctique",
    AG: "Antigua-et-Barbuda",
    AN: "Antilles néerlandaises",
    SA: "Arabie saoudite",
    AR: "Argentine",
    AM: "Arménie",
    AW: "Aruba",
    AU: "Australie",
    AT: "Autriche",
    AZ: "Azerbaïdjan",
    BS: "Bahamas",
    BH: "Bahreïn",
    BD: "Bangladesh",
    BB: "Barbade",
    BY: "Bélarus",
    BE: "Belgique",
    BZ: "Belize",
    BJ: "Bénin",
    BM: "Bermudes",
    BT: "Bhoutan",
    BO: "Bolivie",
    BA: "Bosnie-Herzégovine",
    BW: "Botswana",
    BR: "Brésil",
    BN: "Brunéi Darussalam",
    BG: "Bulgarie",
    BF: "Burkina Faso",
    BI: "Burundi",
    KH: "Cambodge",
    CM: "Cameroun",
    CA: "Canada",
    CV: "Cap-Vert",
    EA: "Ceuta et Melilla",
    CL: "Chili",
    CN: "Chine",
    CY: "Chypre",
    CO: "Colombie",
    KM: "Comores",
    CG: "Congo-Brazzaville",
    KP: "Corée du Nord",
    KR: "Corée du Sud",
    CR: "Costa Rica",
    CI: "Côte d’Ivoire",
    HR: "Croatie",
    CU: "Cuba",
    DK: "Danemark",
    DG: "Diego Garcia",
    DJ: "Djibouti",
    DM: "Dominique",
    EG: "Égypte",
    SV: "El Salvador",
    AE: "Émirats arabes unis",
    EC: "Équateur",
    ER: "Érythrée",
    ES: "Espagne",
    EE: "Estonie",
    VA: "État de la Cité du Vatican",
    FM: "États fédérés de Micronésie",
    US: "États-Unis",
    ET: "Éthiopie",
    FJ: "Fidji",
    FI: "Finlande",
    FR: "France",
    GA: "Gabon",
    GM: "Gambie",
    GE: "Géorgie",
    GS: "Géorgie du Sud et les îles Sandwich du Sud",
    GH: "Ghana",
    GI: "Gibraltar",
    GR: "Grèce",
    GD: "Grenade",
    GL: "Groenland",
    GP: "Guadeloupe",
    GU: "Guam",
    GT: "Guatemala",
    GG: "Guernesey",
    GN: "Guinée",
    GQ: "Guinée équatoriale",
    GW: "Guinée-Bissau",
    GY: "Guyana",
    GF: "Guyane française",
    HT: "Haïti",
    HN: "Honduras",
    HU: "Hongrie",
    BV: "Île Bouvet",
    CX: "Île Christmas",
    CP: "Île Clipperton",
    AC: "Île de l'Ascension",
    IM: "Île de Man",
    NF: "Île Norfolk",
    AX: "Îles Åland",
    KY: "Îles Caïmans",
    IC: "Îles Canaries",
    CC: "Îles Cocos - Keeling",
    CK: "Îles Cook",
    FO: "Îles Féroé",
    HM: "Îles Heard et MacDonald",
    FK: "Îles Malouines",
    MP: "Îles Mariannes du Nord",
    MH: "Îles Marshall",
    UM: "Îles Mineures Éloignées des États-Unis",
    SB: "Îles Salomon",
    TC: "Îles Turks et Caïques",
    VG: "Îles Vierges britanniques",
    VI: "Îles Vierges des États-Unis",
    IN: "Inde",
    ID: "Indonésie",
    IQ: "Irak",
    IR: "Iran",
    IE: "Irlande",
    IS: "Islande",
    IL: "Israël",
    IT: "Italie",
    JM: "Jamaïque",
    JP: "Japon",
    JE: "Jersey",
    JO: "Jordanie",
    KZ: "Kazakhstan",
    KE: "Kenya",
    KG: "Kirghizistan",
    KI: "Kiribati",
    KW: "Koweït",
    LA: "Laos",
    LS: "Lesotho",
    LV: "Lettonie",
    LB: "Liban",
    LR: "Libéria",
    LY: "Libye",
    LI: "Liechtenstein",
    LT: "Lituanie",
    LU: "Luxembourg",
    MK: "Macédoine",
    MG: "Madagascar",
    MY: "Malaisie",
    MW: "Malawi",
    MV: "Maldives",
    ML: "Mali",
    MT: "Malte",
    MA: "Maroc",
    MQ: "Martinique",
    MU: "Maurice",
    MR: "Mauritanie",
    YT: "Mayotte",
    MX: "Mexique",
    MD: "Moldavie",
    MC: "Monaco",
    MN: "Mongolie",
    ME: "Monténégro",
    MS: "Montserrat",
    MZ: "Mozambique",
    MM: "Myanmar",
    NA: "Namibie",
    NR: "Nauru",
    NP: "Népal",
    NI: "Nicaragua",
    NE: "Niger",
    NG: "Nigéria",
    NU: "Niue",
    NO: "Norvège",
    NC: "Nouvelle-Calédonie",
    NZ: "Nouvelle-Zélande",
    OM: "Oman",
    UG: "Ouganda",
    UZ: "Ouzbékistan",
    PK: "Pakistan",
    PW: "Palaos",
    PA: "Panama",
    PG: "Papouasie-Nouvelle-Guinée",
    PY: "Paraguay",
    NL: "Pays-Bas",
    PE: "Pérou",
    PH: "Philippines",
    PN: "Pitcairn",
    PL: "Pologne",
    PF: "Polynésie française",
    PR: "Porto Rico",
    PT: "Portugal",
    QA: "Qatar",
    HK: "R.A.S. chinoise de Hong Kong",
    MO: "R.A.S. chinoise de Macao",
    QO: "régions éloignées de l’Océanie",
    CF: "République centrafricaine",
    CD: "République démocratique du Congo",
    DO: "République dominicaine",
    CZ: "République tchèque",
    RE: "Réunion",
    RO: "Roumanie",
    GB: "Royaume-Uni",
    RU: "Russie",
    RW: "Rwanda",
    EH: "Sahara occidental",
    BL: "Saint-Barthélémy",
    KN: "Saint-Kitts-et-Nevis",
    SM: "Saint-Marin",
    MF: "Saint-Martin",
    PM: "Saint-Pierre-et-Miquelon",
    VC: "Saint-Vincent-et-les Grenadines",
    SH: "Sainte-Hélène",
    LC: "Sainte-Lucie",
    WS: "Samoa",
    AS: "Samoa américaines",
    ST: "Sao Tomé-et-Principe",
    SN: "Sénégal",
    RS: "Serbie",
    CS: "Serbie-et-Monténégro",
    SC: "Seychelles",
    SL: "Sierra Leone",
    SG: "Singapour",
    SK: "Slovaquie",
    SI: "Slovénie",
    SO: "Somalie",
    SD: "Soudan",
    LK: "Sri Lanka",
    SE: "Suède",
    CH: "Suisse",
    SR: "Suriname",
    SJ: "Svalbard et Île Jan Mayen",
    SZ: "Swaziland",
    SY: "Syrie",
    TJ: "Tadjikistan",
    TW: "Taïwan",
    TZ: "Tanzanie",
    TD: "Tchad",
    TF: "Terres australes françaises",
    IO: "Territoire britannique de l'océan Indien",
    PS: "Territoire palestinien",
    TH: "Thaïlande",
    TL: "Timor oriental",
    TG: "Togo",
    TK: "Tokelau",
    TO: "Tonga",
    TT: "Trinité-et-Tobago",
    TA: "Tristan da Cunha",
    TN: "Tunisie",
    TM: "Turkménistan",
    TR: "Turquie",
    TV: "Tuvalu",
    UA: "Ukraine",
    EU: "Union européenne",
    UY: "Uruguay",
    VU: "Vanuatu",
    VE: "Venezuela",
    VN: "Viêt Nam",
    WF: "Wallis-et-Futuna",
    YE: "Yémen",
    ZM: "Zambie",
    ZW: "Zimbabwe",
  },
  de: {
    AF: "Afghanistan",
    EG: "Ägypten",
    AX: "Åland",
    AL: "Albanien",
    DZ: "Algerien",
    AS: "Amerikanisch-Samoa",
    VI: "Amerikanische Jungferninseln",
    AD: "Andorra",
    AO: "Angola",
    AI: "Anguilla",
    AQ: "Antarktis (Sonderstatus durch Antarktisvertrag)",
    AG: "Antigua und Barbuda",
    GQ: "Äquatorialguinea",
    AR: "Argentinien",
    AM: "Armenien",
    AW: "Aruba",
    AZ: "Aserbaidschan",
    ET: "Äthiopien",
    AU: "Australien",
    BS: "Bahamas",
    BH: "Bahrain",
    BD: "Bangladesch",
    BB: "Barbados",
    BY: "Belarus",
    BE: "Belgien",
    BZ: "Belize",
    BJ: "Benin",
    BM: "Bermuda",
    BT: "Bhutan",
    BO: "Bolivien",
    BQ: "Bonaire, Saba, Sint Eustatius",
    BA: "Bosnien und Herzegowina",
    BW: "Botswana",
    BV: "Bouvetinsel",
    BR: "Brasilien",
    VG: "Britische Jungferninseln",
    IO: "Britisches Territorium im Indischen Ozean",
    BN: "Brunei",
    BG: "Bulgarien",
    BF: "Burkina Faso",
    BI: "Burundi",
    CL: "Chile",
    CN: "Volksrepublik China",
    CK: "Cookinseln",
    CR: "Costa Rica",
    CW: "Curaçao",
    DK: "Dänemark",
    DE: "Deutschland",
    DM: "Dominica",
    DO: "Dominikanische Republik",
    DJ: "Dschibuti",
    EC: "Ecuador",
    CI: "Elfenbeinküste",
    SV: "El Salvador",
    ER: "Eritrea",
    EE: "Estland",
    SZ: "Eswatini",
    FK: "Falklandinseln",
    FO: "Färöer",
    FJ: "Fidschi",
    FI: "Finnland",
    FR: "Frankreich",
    GF: "Französisch-Guayana",
    PF: "Französisch-Polynesien",
    TF: "Französische Süd- und Antarktisgebiete",
    GA: "Gabun",
    GM: "Gambia",
    GE: "Georgien",
    GH: "Ghana",
    GI: "Gibraltar",
    GD: "Grenada",
    GR: "Griechenland",
    GL: "Grönland",
    GP: "Guadeloupe",
    GU: "Guam",
    GT: "Guatemala",
    GG: "Guernsey (Kanalinsel)",
    GN: "Guinea",
    GW: "Guinea-Bissau",
    GY: "Guyana",
    HT: "Haiti",
    HM: "Heard und McDonaldinseln",
    HN: "Honduras",
    HK: "Hongkong",
    IN: "Indien",
    ID: "Indonesien",
    IM: "Insel Man",
    IQ: "Irak",
    IR: "Iran",
    IE: "Irland",
    IS: "Island",
    IL: "Israel",
    IT: "Italien",
    JM: "Jamaika",
    JP: "Japan",
    YE: "Jemen",
    JE: "Jersey (Kanalinsel)",
    JO: "Jordanien",
    KY: "Kaimaninseln",
    KH: "Kambodscha",
    CM: "Kamerun",
    CA: "Kanada",
    CV: "Kap Verde",
    KZ: "Kasachstan",
    QA: "Katar",
    KE: "Kenia",
    KG: "Kirgisistan",
    KI: "Kiribati",
    CC: "Kokosinseln",
    CO: "Kolumbien",
    KM: "Komoren",
    CD: "Kongo, Demokratische Republik",
    CG: "Kongo, Republik",
    KP: "Korea, Nord",
    KR: "Korea, Süd",
    HR: "Kroatien",
    CU: "Kuba",
    KW: "Kuwait",
    LA: "Laos",
    LS: "Lesotho",
    LV: "Lettland",
    LB: "Libanon",
    LR: "Liberia",
    LY: "Libyen",
    LI: "Liechtenstein",
    LT: "Litauen",
    LU: "Luxemburg",
    MO: "Macau",
    MG: "Madagaskar",
    MW: "Malawi",
    MY: "Malaysia",
    MV: "Malediven",
    ML: "Mali",
    MT: "Malta",
    MA: "Marokko",
    MH: "Marshallinseln",
    MQ: "Martinique",
    MR: "Mauretanien",
    MU: "Mauritius",
    YT: "Mayotte",
    MX: "Mexiko",
    FM: "Mikronesien",
    MD: "Moldau",
    MC: "Monaco",
    MN: "Mongolei",
    ME: "Montenegro",
    MS: "Montserrat",
    MZ: "Mosambik",
    MM: "Myanmar",
    NA: "Namibia",
    NR: "Nauru",
    NP: "Nepal",
    NC: "Neukaledonien",
    NZ: "Neuseeland",
    NI: "Nicaragua",
    NL: "Niederlande",
    NE: "Niger",
    NG: "Nigeria",
    NU: "Niue",
    MP: "Nördliche Marianen",
    MK: "Nordmazedonien",
    NF: "Norfolkinsel",
    NO: "Norwegen",
    OM: "Oman",
    AT: "Österreich",
    TL: "Osttimor",
    PK: "Pakistan",
    PS: "Palästina",
    PW: "Palau",
    PA: "Panama",
    PG: "Papua-Neuguinea",
    PY: "Paraguay",
    PE: "Peru",
    PH: "Philippinen",
    PN: "Pitcairninseln",
    PL: "Polen",
    PT: "Portugal",
    PR: "Puerto Rico",
    RE: "Réunion",
    RW: "Ruanda",
    RO: "Rumänien",
    RU: "Russland",
    SB: "Salomonen",
    BL: "Saint-Barthélemy",
    MF: "Saint-Martin (französischer Teil)",
    ZM: "Sambia",
    WS: "Samoa",
    SM: "San Marino",
    ST: "São Tomé und Príncipe",
    SA: "Saudi-Arabien",
    SE: "Schweden",
    CH: "Schweiz",
    SN: "Senegal",
    RS: "Serbien",
    SC: "Seychellen",
    SL: "Sierra Leone",
    ZW: "Simbabwe",
    SG: "Singapur",
    SX: "Sint Maarten",
    SK: "Slowakei",
    SI: "Slowenien",
    SO: "Somalia",
    ES: "Spanien",
    LK: "Sri Lanka",
    SH: "St. Helena, Ascension und Tristan da Cunha",
    KN: "St. Kitts und Nevis",
    LC: "St. Lucia",
    PM: "Saint-Pierre und Miquelon",
    VC: "St. Vincent und die Grenadinen",
    ZA: "Südafrika",
    SD: "Sudan",
    GS: "Südgeorgien und die Südlichen Sandwichinseln",
    SS: "Südsudan",
    SR: "Suriname",
    SJ: "Spitzbergen und Jan Mayen",
    SY: "Syrien",
    TJ: "Tadschikistan",
    TW: "Republik China",
    TZ: "Tansania",
    TH: "Thailand",
    TG: "Togo",
    TK: "Tokelau",
    TO: "Tonga",
    TT: "Trinidad und Tobago",
    TD: "Tschad",
    CZ: "Tschechien",
    TN: "Tunesien",
    TR: "Türkei",
    TM: "Turkmenistan",
    TC: "Turks- und Caicosinseln",
    TV: "Tuvalu",
    UG: "Uganda",
    UA: "Ukraine",
    HU: "Ungarn",
    UM: "United States Minor Outlying Islands",
    UY: "Uruguay",
    UZ: "Usbekistan",
    VU: "Vanuatu",
    VA: "Vatikanstadt",
    VE: "Venezuela",
    AE: "Vereinigte Arabische Emirate",
    US: "Vereinigte Staaten",
    GB: "Vereinigtes Königreich",
    VN: "Vietnam",
    WF: "Wallis und Futuna",
    CX: "Weihnachtsinsel",
    EH: "Westsahara",
    CF: "Zentralafrikanische Republik",
    CY: "Zypern",
  },
};

export const CountryFlags = {
  AF: require(`../../assets/flags/AF.png`),
  ZA: require(`../../assets/flags/ZA.png`),
  AL: require(`../../assets/flags/AL.png`),
  DZ: require(`../../assets/flags/DZ.png`),
  DE: require(`../../assets/flags/DE.png`),
  AD: require(`../../assets/flags/AD.png`),
  AO: require(`../../assets/flags/AO.png`),
  AI: require(`../../assets/flags/AI.png`),
  AQ: require(`../../assets/flags/AQ.png`),
  AG: require(`../../assets/flags/AG.png`),
  SA: require(`../../assets/flags/SA.png`),
  AR: require(`../../assets/flags/AR.png`),
  AM: require(`../../assets/flags/AM.png`),
  AW: require(`../../assets/flags/AW.png`),
  AU: require(`../../assets/flags/AU.png`),
  AT: require(`../../assets/flags/AT.png`),
  AZ: require(`../../assets/flags/AZ.png`),
  BS: require(`../../assets/flags/BS.png`),
  BH: require(`../../assets/flags/BH.png`),
  BD: require(`../../assets/flags/BD.png`),
  BB: require(`../../assets/flags/BB.png`),
  BY: require(`../../assets/flags/BY.png`),
  BE: require(`../../assets/flags/BE.png`),
  BZ: require(`../../assets/flags/BZ.png`),
  BJ: require(`../../assets/flags/BJ.png`),
  BM: require(`../../assets/flags/BM.png`),
  BT: require(`../../assets/flags/BT.png`),
  BO: require(`../../assets/flags/BO.png`),
  BA: require(`../../assets/flags/BA.png`),
  BW: require(`../../assets/flags/BW.png`),
  BR: require(`../../assets/flags/BR.png`),
  BN: require(`../../assets/flags/BN.png`),
  BG: require(`../../assets/flags/BG.png`),
  BF: require(`../../assets/flags/BF.png`),
  BI: require(`../../assets/flags/BI.png`),
  KH: require(`../../assets/flags/KH.png`),
  CM: require(`../../assets/flags/CM.png`),
  CA: require(`../../assets/flags/CA.png`),
  CV: require(`../../assets/flags/CV.png`),
  CL: require(`../../assets/flags/CL.png`),
  CN: require(`../../assets/flags/CN.png`),
  CY: require(`../../assets/flags/CY.png`),
  CO: require(`../../assets/flags/CO.png`),
  KM: require(`../../assets/flags/KM.png`),
  CG: require(`../../assets/flags/CG.png`),
  KP: require(`../../assets/flags/KP.png`),
  KR: require(`../../assets/flags/KR.png`),
  CR: require(`../../assets/flags/CR.png`),
  CI: require(`../../assets/flags/CI.png`),
  HR: require(`../../assets/flags/HR.png`),
  CU: require(`../../assets/flags/CU.png`),
  DK: require(`../../assets/flags/DK.png`),
  DJ: require(`../../assets/flags/DJ.png`),
  DM: require(`../../assets/flags/DM.png`),
  EG: require(`../../assets/flags/EG.png`),
  SV: require(`../../assets/flags/SV.png`),
  AE: require(`../../assets/flags/AE.png`),
  EC: require(`../../assets/flags/EC.png`),
  ER: require(`../../assets/flags/ER.png`),
  ES: require(`../../assets/flags/ES.png`),
  EE: require(`../../assets/flags/EE.png`),
  VA: require(`../../assets/flags/VA.png`),
  FM: require(`../../assets/flags/FM.png`),
  US: require(`../../assets/flags/US.png`),
  ET: require(`../../assets/flags/ET.png`),
  FJ: require(`../../assets/flags/FJ.png`),
  FI: require(`../../assets/flags/FI.png`),
  FR: require(`../../assets/flags/FR.png`),
  GA: require(`../../assets/flags/GA.png`),
  GM: require(`../../assets/flags/GM.png`),
  GE: require(`../../assets/flags/GE.png`),
  GS: require(`../../assets/flags/GS.png`),
  GH: require(`../../assets/flags/GH.png`),
  GI: require(`../../assets/flags/GI.png`),
  GR: require(`../../assets/flags/GR.png`),
  GD: require(`../../assets/flags/GD.png`),
  GL: require(`../../assets/flags/GL.png`),
  GP: require(`../../assets/flags/GP.png`),
  GU: require(`../../assets/flags/GU.png`),
  GT: require(`../../assets/flags/GT.png`),
  GG: require(`../../assets/flags/GG.png`),
  GN: require(`../../assets/flags/GN.png`),
  GQ: require(`../../assets/flags/GQ.png`),
  GW: require(`../../assets/flags/GW.png`),
  GY: require(`../../assets/flags/GY.png`),
  GF: require(`../../assets/flags/GF.png`),
  HT: require(`../../assets/flags/HT.png`),
  HN: require(`../../assets/flags/HN.png`),
  HU: require(`../../assets/flags/HU.png`),
  BV: require(`../../assets/flags/BV.png`),
  CX: require(`../../assets/flags/CX.png`),
  IM: require(`../../assets/flags/IM.png`),
  NF: require(`../../assets/flags/NF.png`),
  AX: require(`../../assets/flags/AX.png`),
  KY: require(`../../assets/flags/KY.png`),
  CC: require(`../../assets/flags/CC.png`),
  CK: require(`../../assets/flags/CK.png`),
  FO: require(`../../assets/flags/FO.png`),
  HM: require(`../../assets/flags/HM.png`),
  FK: require(`../../assets/flags/FK.png`),
  MP: require(`../../assets/flags/MP.png`),
  MH: require(`../../assets/flags/MH.png`),
  UM: require(`../../assets/flags/UM.png`),
  SB: require(`../../assets/flags/SB.png`),
  TC: require(`../../assets/flags/TC.png`),
  VG: require(`../../assets/flags/VG.png`),
  VI: require(`../../assets/flags/VI.png`),
  IN: require(`../../assets/flags/IN.png`),
  ID: require(`../../assets/flags/ID.png`),
  IQ: require(`../../assets/flags/IQ.png`),
  IR: require(`../../assets/flags/IR.png`),
  IE: require(`../../assets/flags/IE.png`),
  IS: require(`../../assets/flags/IS.png`),
  IL: require(`../../assets/flags/IL.png`),
  IT: require(`../../assets/flags/IT.png`),
  JM: require(`../../assets/flags/JM.png`),
  JP: require(`../../assets/flags/JP.png`),
  JE: require(`../../assets/flags/JE.png`),
  JO: require(`../../assets/flags/JO.png`),
  KZ: require(`../../assets/flags/KZ.png`),
  KE: require(`../../assets/flags/KE.png`),
  KG: require(`../../assets/flags/KG.png`),
  KI: require(`../../assets/flags/KI.png`),
  KW: require(`../../assets/flags/KW.png`),
  LA: require(`../../assets/flags/LA.png`),
  LS: require(`../../assets/flags/LS.png`),
  LV: require(`../../assets/flags/LV.png`),
  LB: require(`../../assets/flags/LB.png`),
  LR: require(`../../assets/flags/LR.png`),
  LY: require(`../../assets/flags/LY.png`),
  LI: require(`../../assets/flags/LI.png`),
  LT: require(`../../assets/flags/LT.png`),
  LU: require(`../../assets/flags/LU.png`),
  MK: require(`../../assets/flags/MK.png`),
  MG: require(`../../assets/flags/MG.png`),
  MY: require(`../../assets/flags/MY.png`),
  MW: require(`../../assets/flags/MW.png`),
  MV: require(`../../assets/flags/MV.png`),
  ML: require(`../../assets/flags/ML.png`),
  MT: require(`../../assets/flags/MT.png`),
  MA: require(`../../assets/flags/MA.png`),
  MQ: require(`../../assets/flags/MQ.png`),
  MU: require(`../../assets/flags/MU.png`),
  MR: require(`../../assets/flags/MR.png`),
  YT: require(`../../assets/flags/YT.png`),
  MX: require(`../../assets/flags/MX.png`),
  MD: require(`../../assets/flags/MD.png`),
  MC: require(`../../assets/flags/MC.png`),
  MN: require(`../../assets/flags/MN.png`),
  ME: require(`../../assets/flags/ME.png`),
  MS: require(`../../assets/flags/MS.png`),
  MZ: require(`../../assets/flags/MZ.png`),
  MM: require(`../../assets/flags/MM.png`),
  NA: require(`../../assets/flags/NA.png`),
  NR: require(`../../assets/flags/NR.png`),
  NP: require(`../../assets/flags/NP.png`),
  NI: require(`../../assets/flags/NI.png`),
  NE: require(`../../assets/flags/NE.png`),
  NG: require(`../../assets/flags/NG.png`),
  NU: require(`../../assets/flags/NU.png`),
  NO: require(`../../assets/flags/NO.png`),
  NC: require(`../../assets/flags/NC.png`),
  NZ: require(`../../assets/flags/NZ.png`),
  OM: require(`../../assets/flags/OM.png`),
  UG: require(`../../assets/flags/UG.png`),
  UZ: require(`../../assets/flags/UZ.png`),
  PK: require(`../../assets/flags/PK.png`),
  PW: require(`../../assets/flags/PW.png`),
  PA: require(`../../assets/flags/PA.png`),
  PG: require(`../../assets/flags/PG.png`),
  PY: require(`../../assets/flags/PY.png`),
  NL: require(`../../assets/flags/NL.png`),
  PE: require(`../../assets/flags/PE.png`),
  PH: require(`../../assets/flags/PH.png`),
  PN: require(`../../assets/flags/PN.png`),
  PL: require(`../../assets/flags/PL.png`),
  PF: require(`../../assets/flags/PF.png`),
  PR: require(`../../assets/flags/PR.png`),
  PT: require(`../../assets/flags/PT.png`),
  QA: require(`../../assets/flags/QA.png`),
  HK: require(`../../assets/flags/HK.png`),
  MO: require(`../../assets/flags/MO.png`),
  CF: require(`../../assets/flags/CF.png`),
  CD: require(`../../assets/flags/CD.png`),
  DO: require(`../../assets/flags/DO.png`),
  CZ: require(`../../assets/flags/CZ.png`),
  RE: require(`../../assets/flags/RE.png`),
  RO: require(`../../assets/flags/RO.png`),
  GB: require(`../../assets/flags/GB.png`),
  RU: require(`../../assets/flags/RU.png`),
  RW: require(`../../assets/flags/RW.png`),
  EH: require(`../../assets/flags/EH.png`),
  BL: require(`../../assets/flags/BL.png`),
  KN: require(`../../assets/flags/KN.png`),
  SM: require(`../../assets/flags/SM.png`),
  MF: require(`../../assets/flags/MF.png`),
  PM: require(`../../assets/flags/PM.png`),
  VC: require(`../../assets/flags/VC.png`),
  SH: require(`../../assets/flags/SH.png`),
  LC: require(`../../assets/flags/LC.png`),
  WS: require(`../../assets/flags/WS.png`),
  AS: require(`../../assets/flags/AS.png`),
  ST: require(`../../assets/flags/ST.png`),
  SN: require(`../../assets/flags/SN.png`),
  RS: require(`../../assets/flags/RS.png`),
  SC: require(`../../assets/flags/SC.png`),
  SL: require(`../../assets/flags/SL.png`),
  SG: require(`../../assets/flags/SG.png`),
  SK: require(`../../assets/flags/SK.png`),
  SI: require(`../../assets/flags/SI.png`),
  SO: require(`../../assets/flags/SO.png`),
  SD: require(`../../assets/flags/SD.png`),
  LK: require(`../../assets/flags/LK.png`),
  SE: require(`../../assets/flags/SE.png`),
  CH: require(`../../assets/flags/CH.png`),
  SR: require(`../../assets/flags/SR.png`),
  SJ: require(`../../assets/flags/SJ.png`),
  SZ: require(`../../assets/flags/SZ.png`),
  SY: require(`../../assets/flags/SY.png`),
  TJ: require(`../../assets/flags/TJ.png`),
  TW: require(`../../assets/flags/TW.png`),
  TZ: require(`../../assets/flags/TZ.png`),
  TD: require(`../../assets/flags/TD.png`),
  TF: require(`../../assets/flags/TF.png`),
  IO: require(`../../assets/flags/IO.png`),
  PS: require(`../../assets/flags/PS.png`),
  TH: require(`../../assets/flags/TH.png`),
  TL: require(`../../assets/flags/TL.png`),
  TG: require(`../../assets/flags/TG.png`),
  TK: require(`../../assets/flags/TK.png`),
  TO: require(`../../assets/flags/TO.png`),
  TT: require(`../../assets/flags/TT.png`),
  TN: require(`../../assets/flags/TN.png`),
  TM: require(`../../assets/flags/TM.png`),
  TR: require(`../../assets/flags/TR.png`),
  TV: require(`../../assets/flags/TV.png`),
  UA: require(`../../assets/flags/UA.png`),
  UY: require(`../../assets/flags/UY.png`),
  VU: require(`../../assets/flags/VU.png`),
  VE: require(`../../assets/flags/VE.png`),
  VN: require(`../../assets/flags/VN.png`),
  WF: require(`../../assets/flags/WF.png`),
  YE: require(`../../assets/flags/YE.png`),
  ZM: require(`../../assets/flags/ZM.png`),
  ZW: require(`../../assets/flags/ZW.png`),
};
